#cloud-config
write_files:
  - path: /etc/fahclient/config.xml 
    content: |
      <config>
        <user value=''/>
        <team value='246715'/>
        <passkey value=''/>
        <power value='full'/>
        <gpu value='false'/>
        <fold-anon value='false'/>
        <allow>x.x.x.x</allow>
        <web-allow>x.x.x.x</web-allow>
        <password></password>
      </config>

runcmd:
  - mkdir /run/folding
  - [ wget, "https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.5/fahclient_7.5.1_amd64.deb", -O, /run/folding/fahclient_7.5.1_amd64.deb ]
  - DEBIAN_FRONTEND=noninteractive apt-get install -y /run/folding/fahclient_7.5.1_amd64.deb